name: CI workflow

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Python - Run unittests
      run: python -m unittest discover
    - name: build
      run: npm run build
    - name: Nodejs - Run unittests
      run: npm run test
    - name: Build coverage file
      run: |
        python -m pytest --cache-clear > pytest-coverage.txt
    - name: Comment coverage
      uses: coroo/pytest-coverage-commentator@v1.0.2
